name: Flutter - Android Development

on:
  push:
    branches:
      - main
    

jobs: 
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: 'stable'
          

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: check flutter doctor
        run: flutter doctor -v

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
