name: Flutter - Web Development

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: 'stable'


      - name: Install dependencies
        run: flutter pub get

      - name: check flutter doctor
        run: flutter doctor -v

      - name: Build flutter Web app
        run: flutter build web --release

      - name: Upload Web App artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/web

      - name: upload to github
        run: |
          cd build/web
#          git remote add origin https://github.com/Dani-abera/Dani-abera.github.io.git
          git remote -v
          git push -u origin main
          
  

#  git remote add origin https://github.com/Dani-abera/Dani-abera.github.io.git
#  git branch -M main
#  git push -u origin main
